cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('cars/', views.CarsCatalogView.as_view(), name='main'),
    path('brands/<slug:brand_slug>/', views.CarsView.as_view(), name='brands'),
    path('brands/model/<slug:model_slug>/', views.CarsDetailView.as_view(), name='models')
]

cs/urls.py
from django.urls import path
from cs import views

app_name = 'cs'

urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
]

news/urls.py
from django.urls import path, include

from news import views

app_name = 'news'

urlpatterns = [
    path('news/', views.NewsHomeView.as_view(), name='news'),
    path('news/<slug:slug>/', views.NewsPostsView.as_view(), name='news_by_category'),
    path('news/detail/<slug:slug>/', views.DetailNewsView.as_view(), name='detail_news'),

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cs.urls', namespace='cs')),
    path('', include('news.urls', namespace='news')),
    path('', include('cars.urls', namespace='cars')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/models.py
from django.db import models
from django.urls import reverse


class Brand(models.Model):
    name = models.CharField(max_length=100, verbose_name='Бренд')
    slug = models.SlugField(max_length=250, verbose_name='Слаг Бренда', unique=True)

    def get_absolute_url(self):
        return reverse('cars:brands', kwargs={'brand_slug': self.slug})

    def __str__(self):
        return self.name


class CarModel(models.Model):
    name = models.CharField(max_length=100, verbose_name='Модель автомобиля')
    slug = models.SlugField(max_length=250, verbose_name='Слаг модели', unique=True)
    image = models.ImageField(upload_to='cars_catalog', verbose_name='Изображение автомобиля', default=None, null=True,
                              blank=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('cars:models', kwargs={'model_slug': self.slug})

    def __str__(self):
        return f'{self.brand.name} | {self.name}'

cs/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.urls import reverse


class NewsCategory(models.Model):
    name = models.CharField(max_length=100,
                            verbose_name='Наименование категории')

    slug = models.SlugField(max_length=255,
                            verbose_name='Слаг категории',
                            unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('news:news_by_category', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Категория Новости'
        verbose_name_plural = 'Категории Новостей'


class NewsPost(models.Model):
    title = models.CharField(max_length=100,
                             verbose_name='Заголовок поста',
                             blank=False)

    slug = models.SlugField(max_length=255,
                            verbose_name='Слаг поста',
                            unique=True)

    description = models.TextField(verbose_name='Содержание поста')

    image = models.ImageField(upload_to='post_images',
                              verbose_name='Изображение поста',
                              default=None,
                              blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    category = models.ForeignKey(NewsCategory,
                                 on_delete=models.CASCADE,
                                 related_name='post')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news:detail_news', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Категория Поста'
        verbose_name_plural = 'Категории Постов'

cars/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView

from .models import Brand, CarModel


class CarsCatalogView(ListView):
    template_name = 'cars/index.html'
    context_object_name = 'brands'

    def get_queryset(self):
        brands = Brand.objects.all()
        return brands

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['models'] = CarModel.objects.all()
        context['brands'] = Brand.objects.all()
        return context


class CarsView(ListView):
    template_name = 'cars/index.html'
    context_object_name = 'models'

    def get_queryset(self):
        return CarModel.objects.filter(brand__slug=self.kwargs['brand_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['brands'] = Brand.objects.all()
        return context


class CarsDetailView(DetailView):
    template_name = 'cars/index.html'
    context_object_name = 'model_image'
    slug_url_kwarg = 'model_slug'

    def get_queryset(self):
        return CarModel.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        selected_model = context['object']
        context['models'] = CarModel.objects.filter(brand=selected_model.brand)
        context['brands'] = Brand.objects.all()
        return context

cs/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from news.models import NewsPost


class HomeView(ListView):
    template_name = 'cs/index.html'
    context_object_name = 'cars_images'
    paginate_by = 1

    def get_queryset(self):
        static_images = [
            '/static/cs/images/car-2.jpg',
            '/static/cs/images/car-1.jpg',
            '/static/cs/images/car-3.jpg',
        ]
        return static_images

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = NewsPost.objects.all()
        return context

news/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from news.models import NewsCategory, NewsPost


class NewsHomeView(ListView):
    template_name = 'news/index.html'
    context_object_name = 'categories_list'

    def get_queryset(self):
        category = NewsCategory.objects.all()
        return category

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = NewsPost.objects.all()
        return context


class NewsPostsView(ListView):
    template_name = 'news/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return NewsPost.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories_list'] = NewsCategory.objects.all()
        return context


class DetailNewsView(DetailView):
    template_name = 'news/detail_news.html'
    context_object_name = 'post'

    def get_queryset(self):
        return NewsPost.objects.all()

cars/templates/cars/detail_model.html
{% extends 'base.html' %}

{% block detail-model %}
    <h1>{{ model_image.name }}</h1>
    <img src="{{ model_image.image.url }}">
{% endblock %}

cars/templates/cars/index.html
{% extends 'base.html' %}
{% load static %}

{% block cars-main %}
  <link rel="stylesheet" href="{% static 'cars/css/cars.css' %}">
    <main class="cars-main">
      <nav class="cars-nav">
        <nav class="web-nav">
          <a class="home-link" href="{% url 'cs:main' %}">HOME</a>
          <a class="news-link" href="{% url 'news:news' %}">NEWS</a>
        </nav>
        <nav class="brands-nav">

          <ul class="all-brands">
            <li><a>BRANDS</a></li>
          </ul>

          <ul class="brands-list">
            {% for brand in brands %}
              <li class="brands-item"><a class="brands-link" href="{{ brand.get_absolute_url }}">{{ brand.name }}</a></li>
            {% endfor %}
          </ul>

        </nav>

        <nav class="models-nav">

          <ul class="all-models">
            <li><a>MODELS</a></li>
          </ul>

          <ul class="models-list">
            {% for model in models %}
              <li class="models-item"><a class="models-link" href="{{ model.get_absolute_url }}">{{ model.name }}</a></li>
            {% endfor %}
          </ul>

        </nav>
      </nav>


      <section class="cars-section">
        {% if model_image %}
          <img src="{{ model_image.image.url }}">
        {% endif %}
      </section>
    </main>
{% endblock %}

cs/templates/cs/index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <link rel="stylesheet" href="{% static 'cs/css/index.css' %}">

    <header class="main-header">
        <div class="main-header-wrapper">
            <div class="main-header-menu">
                <button class="burger-menu-btn">
                    <span></span>
                    <span></span>
                </button>
                <a class="news-link" href="{% url 'news:news' %}">NEWS</a>
            </div>
            <a class="contact-link">CONTACTS</a>
        </div>
    </header>

    <main class="cs-main">
        <section class="welcome-page">
            <div class="welcome-text">
                <h1 class="welcome-title">CLUB SPORT</h1>
                <h2 class="welcome-subtitle">EXPLORE THE AUTOMOTIVE WORLD</h2>
                <div class="welcome-btn">
                    <a class="explore-link" href="#">EXPLORE</a>
                </div>
            </div>
        </section>

        <section class="cars-section">
            <h2 class="cars-title">BRANDS</h2>
            {% for cars in cars_images %}
                <div class="cars-container">
                    <img src="{{ cars }}" class="car-images">
                </div>
            {% endfor %}

            <div class="cars-paginate">

               {% for page_num in page_obj.paginator.page_range %}
                    <span class="current">
                        {% if page_num == page_obj.number %}
                            <a href="?page={{ page_num }}" class="current-page"></a>
                        {% else %}
                            <a href="?page={{ page_num }}" class="pages"></a>
                        {% endif %}
                    </span>
                {% endfor %}

            </div>
        </section>

        <section class="gallery-section">
            <div class="gallery-wrapper">
                <div class="gallery-image-container"><img src="{% static 'cs/images/gallery-4.jpg' %}"></div>
                <div class="gallery-image-container"><img src="{% static 'cs/images/gallery-2.jpg' %}"></div>
                <div class="gallery-image-container"><img src="{% static 'cs/images/gallery-3.jpg' %}"></div>
                <div class="gallery-image-container"><img src="{% static 'cs/images/gallery-1.jpg' %}"></div>
            </div>
        </section>

        <section class="news-section">
            <div class="news-wrapper">
                    <div class="news-text">
                        <div class="news-category">
                            <span>NEWS</span><span>{{ posts.0.category.name }}</span>
                        </div>
                        <div class="news-title">
                            <h1>{{ posts.0.title }}</h1>
                        </div>
                        <div class="news-descr">
                            <p>{{ posts.0.description }}</p>
                        </div>
                        <div class="news-link">
                            <a href="{% url 'news:news' %}">MORE</a>
                            <span>{{ posts.0.created_at|date }}</span>
                        </div>
                    </div>
                    <div class="news-image">
                        <img src="{{ posts.0.image.url }}">
                    </div>
            </div>
        </section>
    </main>

    <footer class="cs-footer">
        <div class="footer-wrapper">
            <h2 class="footer-title">CLUB SPORT</h2>

            <form class="footer-form">
                <p>SUBSCRIBE TO OUR NEWSLETTER FOR ADDITIONAL AND FRESH NEWS</p>
                <div class="footer-subscribe">
                    <input class="footer-email-input" type="text" placeholder="YOUR EMAIL ...">
                    <button class="footer-subsribe-btn" type="submit">SUBSCRIBE</button>
                </div>
            </form>
        </div>
    </footer>
{% endblock %}

news/templates/news/detail_news.html
{% extends 'base.html' %}
{% load static %}

{% block detail_news %}
<link rel="stylesheet" href="{% static 'news/css/detail_news.css' %}">
    <div class="back-to-feed">
        <a class="back-link" href="{% url 'news:news' %}">COME BACK</a>
    </div>

    <section class="detail-post">
        <div class="detail-post-wrapper">
            <div class="post-category-date">
                <div class="post-category">
                    <span>NEWS</span><span>{{ post.category.name }}</span>
                </div>
                <div class="post-date">
                    <span>{{ post.created_at|date }}</span>
                </div>
            </div>
            <div class="post-image">
                <img src="{{ post.image.url }}">
            </div>
            <div class="post-title">
                <h1>{{ post.title }}</h1>
            </div>
            <div class="post-descr">
                {% autoescape on %}
                    <p>{{ post.description|linebreaks }}</p>
                {% endautoescape %}
            </div>
            <div class="post-subscribe-socials">
                <form class="post-subscribe">
                    <input class="subscribe-input" placeholder="Your email...">
                    <button class="subscribe-btn" type="submit">SUBSCRIBE</button>
                </form>
                <div class="post-socials">
                    <a>1</a>
                    <a>2</a>
                    <a>3</a>
                    <a>4</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

news/templates/news/index.html
{% extends 'base.html' %}
{% load static %}

{% block news %}
<link rel="stylesheet" href="{% static 'news/css/index.css' %}">

    <nav class="news-sidebar">
        <ul class="web-nav">
            <li><a class="web-nav-link" href="{% url 'cs:main' %}">HOME</a></li>
            <li><a class="web-nav-link" href="{% url 'cars:main' %}">CARS</a></li>
            <li><a class="web-nav-link" href="{% url 'news:news' %}">CSNEWS</a></li>
        </ul>
        <ul class="news-nav">
            {% for category in categories_list %}
                <li class="news-categories-item"><a class="news-categories-link" href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
    </nav>

    <main class="news-main">
        <section class="news-search">
            <input type="search" class="search-input" placeholder="SEARCH ...">
        </section>

        <section class="news-feed">
            {% for post in posts %}
            <div class="posts-wrapper">

                <div class="post-image">
                    <img src="{{ post.image.url }}">
                </div>

                <div class="post-text">
                    <div class="post-category">
                        <span>NEWS</span><span>{{ post.category.name }}</span>
                    </div>

                    <div class="post-title">
                        <h2>{{ post.title }}</h2>
                    </div>

                    <div class="post-descr">
                        <p>{{ post.description|truncatewords:50 }}</p>
                    </div>

                    <div class="post-detail">
                         <a href="{{ post.get_absolute_url }}" class="post-detail-link">MORE</a>
                         <span class="post-date">{{ post.created_at|date }}</span>
                    </div>
                </div>

            </div>
            {% endfor %}
        </section>
    </main>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block main %}
    {% endblock %}

    {% block news %}
    {% endblock %}

    {% block detail_news %}
    {% endblock %}

    {% block cars-main %}
    {% endblock %}

    {% block detail-model %}
    {% endblock %}
</body>
</html>